---
    - name: Get join token for worker node
      register: join_token_output
      shell: kubeadm token create --print-join-command
      when: inventory_hostname == "master"
    - name: Set fact for join token
      set_fact:
        join_token: "{{ join_token_output.stdout }}"
      when: inventory_hostname == "master"
    - name: Join the worker node to the cluster
      command: kubeadm join {{ master_ip }}:6443 --token {{ join_token }} --discovery-token-unsafe-skip-ca-verification
      when: inventory_hostname == "worker"

