---
    - name: Retrieve Join Command
      hosts: master
      shell: kubeadm token create --print-join-command
      register: join_command_raw
       
    - name: Set Join Command
      hosts: master
      set_fact:
         join_command: "{{ join_command_raw.stdout_lines[0] }}"

    - name: Enable TCP port 6443 (On Master) is able to connect from Worker
      hosts: worker_node
      tasks:
       wait_for: "host=master port=6443 timeout=1"

    - name: Join worker to cluster
      hosts: worker_node
      tasks:
       shell: "{{ master.join_command }} >> node_joined.log"
       args:
         chdir: /home/chiheb
         creates: node_joined.log
